package com.webcore.modle;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.asxsydutils.annotation.Table;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
@Table(dataSourceName="webos", tableName="grouprelationship", primaryKey="id")
public abstract class Grouprelationship<M extends Grouprelationship<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}

	public String getId() {
		return get("id");
	}

	public void setImid(String imid) {
		set("imid", imid);
	}

	public String getImid() {
		return get("imid");
	}

	public void setGroupid(String groupid) {
		set("groupid", groupid);
	}

	public String getGroupid() {
		return get("groupid");
	}

}
