package com.iworkflow.service.modle;

import com.asxsydutils.annotation.Table;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
@JsonInclude(value= JsonInclude.Include.NON_NULL)
@Table(dataSourceName="webos", tableName="Notice", primaryKey="id")
public class Notice<M extends Notice<M>> extends Model<M> implements IBean {

	public void setId(String Id) {
		set("Id", Id);
	}

	public String getUserName() {
		return get("UserName");
	}
	public void setUserName(String UserName) {
		set("UserName", UserName);
	}

	public String getId() {
		return get("Id");
	}
	public void setTitle(String Title) {
		set("Title", Title);
	}

	public String getTitle() {
		return get("Title");
	}

	public void setContents(String Contents) {
		set("Contents", Contents);
	}

	public String getContents() {
		return get("Contents");
	}

	public void setAttachFile(String AttachFile) {
		set("AttachFile", AttachFile);
	}

	public String getAttachFile() {
		return get("AttachFile");
	}

	public void setNoticeType(Integer NoticeType) {
		set("NoticeType", NoticeType);
	}

	public Integer getNoticeType() {
		return get("NoticeType");
	}

	public void setDeptID(String DeptID) {
		set("DeptID", DeptID);
	}

	public String getDeptID() {
		return get("DeptID");
	}

	public void setTop(Integer Top) {
		set("Top", Top);
	}

	public Integer getTop() {
		return get("Top");
	}

	public void setSetTopTime(java.util.Date SetTopTime) {
		if(SetTopTime==null) return;
		set("SetTopTime", new java.sql.Timestamp(SetTopTime.getTime()));
	}

	public java.util.Date getSetTopTime() {
		return get("SetTopTime");
	}

	public void setState(Integer State) {
		set("State", State);
	}

	public Integer getState() {
		return get("State");
	}

	public void setStartTime(java.util.Date StartTime) {
		if(StartTime==null) return;
		set("StartTime", new java.sql.Timestamp(StartTime.getTime()));
	}

	public java.util.Date getStartTime() {
		return get("StartTime");
	}

	public void setStopTime(java.util.Date StopTime) {
		if(StopTime==null) return;
		set("StopTime", new java.sql.Timestamp(StopTime.getTime()));
	}

	public java.util.Date getStopTime() {
		return get("StopTime");
	}

	public void setAddTime(java.util.Date AddTime) {
		if(AddTime==null) return;
		set("AddTime", new java.sql.Timestamp(AddTime.getTime()));
	}

	public java.util.Date getAddTime() {
		return get("AddTime");
	}

	public void setUserID(String UserID) {
		set("UserID", UserID);
	}

	public String getUserID() {
		return get("UserID");
	}

	public void setUsers(String Users) {
		set("Users", Users);
	}

	public String getUsers() {
		return get("Users");
	}

	public void setNote(String Note) {
		set("Note", Note);
	}

	public String getNote() {
		return get("Note");
	}

}
